/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as loginRouteRouteImport } from './routes/(login)/route'
import { Route as landingRouteRouteImport } from './routes/(landing)/route'
import { Route as landingIndexRouteImport } from './routes/(landing)/index'
import { Route as loginOnboardingIndexRouteImport } from './routes/(login)/onboarding/index'
import { Route as loginLoginIndexRouteImport } from './routes/(login)/login/index'
import { Route as loginAuth2faRouteImport } from './routes/(login)/auth/2fa'

const loginRouteRoute = loginRouteRouteImport.update({
  id: '/(login)',
  getParentRoute: () => rootRouteImport,
} as any)
const landingRouteRoute = landingRouteRouteImport.update({
  id: '/(landing)',
  getParentRoute: () => rootRouteImport,
} as any)
const landingIndexRoute = landingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => landingRouteRoute,
} as any)
const loginOnboardingIndexRoute = loginOnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => loginRouteRoute,
} as any)
const loginLoginIndexRoute = loginLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => loginRouteRoute,
} as any)
const loginAuth2faRoute = loginAuth2faRouteImport.update({
  id: '/auth/2fa',
  path: '/auth/2fa',
  getParentRoute: () => loginRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof landingIndexRoute
  '/auth/2fa': typeof loginAuth2faRoute
  '/login/': typeof loginLoginIndexRoute
  '/onboarding/': typeof loginOnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof landingIndexRoute
  '/auth/2fa': typeof loginAuth2faRoute
  '/login': typeof loginLoginIndexRoute
  '/onboarding': typeof loginOnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(landing)': typeof landingRouteRouteWithChildren
  '/(login)': typeof loginRouteRouteWithChildren
  '/(landing)/': typeof landingIndexRoute
  '/(login)/auth/2fa': typeof loginAuth2faRoute
  '/(login)/login/': typeof loginLoginIndexRoute
  '/(login)/onboarding/': typeof loginOnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth/2fa' | '/login/' | '/onboarding/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth/2fa' | '/login' | '/onboarding'
  id:
    | '__root__'
    | '/(landing)'
    | '/(login)'
    | '/(landing)/'
    | '/(login)/auth/2fa'
    | '/(login)/login/'
    | '/(login)/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  landingRouteRoute: typeof landingRouteRouteWithChildren
  loginRouteRoute: typeof loginRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(login)': {
      id: '/(login)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof loginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)': {
      id: '/(landing)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof landingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)/': {
      id: '/(landing)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof landingIndexRouteImport
      parentRoute: typeof landingRouteRoute
    }
    '/(login)/onboarding/': {
      id: '/(login)/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof loginOnboardingIndexRouteImport
      parentRoute: typeof loginRouteRoute
    }
    '/(login)/login/': {
      id: '/(login)/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof loginLoginIndexRouteImport
      parentRoute: typeof loginRouteRoute
    }
    '/(login)/auth/2fa': {
      id: '/(login)/auth/2fa'
      path: '/auth/2fa'
      fullPath: '/auth/2fa'
      preLoaderRoute: typeof loginAuth2faRouteImport
      parentRoute: typeof loginRouteRoute
    }
  }
}

interface landingRouteRouteChildren {
  landingIndexRoute: typeof landingIndexRoute
}

const landingRouteRouteChildren: landingRouteRouteChildren = {
  landingIndexRoute: landingIndexRoute,
}

const landingRouteRouteWithChildren = landingRouteRoute._addFileChildren(
  landingRouteRouteChildren,
)

interface loginRouteRouteChildren {
  loginAuth2faRoute: typeof loginAuth2faRoute
  loginLoginIndexRoute: typeof loginLoginIndexRoute
  loginOnboardingIndexRoute: typeof loginOnboardingIndexRoute
}

const loginRouteRouteChildren: loginRouteRouteChildren = {
  loginAuth2faRoute: loginAuth2faRoute,
  loginLoginIndexRoute: loginLoginIndexRoute,
  loginOnboardingIndexRoute: loginOnboardingIndexRoute,
}

const loginRouteRouteWithChildren = loginRouteRoute._addFileChildren(
  loginRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  landingRouteRoute: landingRouteRouteWithChildren,
  loginRouteRoute: loginRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
