/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as loginRouteRouteImport } from './routes/(login)/route'
import { Route as landingRouteRouteImport } from './routes/(landing)/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as landingIndexRouteImport } from './routes/(landing)/index'
import { Route as loginOnboardingIndexRouteImport } from './routes/(login)/onboarding/index'
import { Route as loginLoginIndexRouteImport } from './routes/(login)/login/index'
import { Route as appSettingsIndexRouteImport } from './routes/(app)/settings/index'
import { Route as loginAuth2faRouteImport } from './routes/(login)/auth/2fa'
import { Route as appSettingsProfileRouteImport } from './routes/(app)/settings/profile'
import { Route as appSettingsPrivacyRouteImport } from './routes/(app)/settings/privacy'
import { Route as appSettingsGeneralRouteImport } from './routes/(app)/settings/general'
import { Route as appSettingsAccountRouteImport } from './routes/(app)/settings/account'
import { Route as appSettingsAboutRouteImport } from './routes/(app)/settings/about'

const loginRouteRoute = loginRouteRouteImport.update({
  id: '/(login)',
  getParentRoute: () => rootRouteImport,
} as any)
const landingRouteRoute = landingRouteRouteImport.update({
  id: '/(landing)',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const landingIndexRoute = landingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => landingRouteRoute,
} as any)
const loginOnboardingIndexRoute = loginOnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => loginRouteRoute,
} as any)
const loginLoginIndexRoute = loginLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => loginRouteRoute,
} as any)
const appSettingsIndexRoute = appSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => appRouteRoute,
} as any)
const loginAuth2faRoute = loginAuth2faRouteImport.update({
  id: '/auth/2fa',
  path: '/auth/2fa',
  getParentRoute: () => loginRouteRoute,
} as any)
const appSettingsProfileRoute = appSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => appRouteRoute,
} as any)
const appSettingsPrivacyRoute = appSettingsPrivacyRouteImport.update({
  id: '/settings/privacy',
  path: '/settings/privacy',
  getParentRoute: () => appRouteRoute,
} as any)
const appSettingsGeneralRoute = appSettingsGeneralRouteImport.update({
  id: '/settings/general',
  path: '/settings/general',
  getParentRoute: () => appRouteRoute,
} as any)
const appSettingsAccountRoute = appSettingsAccountRouteImport.update({
  id: '/settings/account',
  path: '/settings/account',
  getParentRoute: () => appRouteRoute,
} as any)
const appSettingsAboutRoute = appSettingsAboutRouteImport.update({
  id: '/settings/about',
  path: '/settings/about',
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof landingIndexRoute
  '/settings/about': typeof appSettingsAboutRoute
  '/settings/account': typeof appSettingsAccountRoute
  '/settings/general': typeof appSettingsGeneralRoute
  '/settings/privacy': typeof appSettingsPrivacyRoute
  '/settings/profile': typeof appSettingsProfileRoute
  '/auth/2fa': typeof loginAuth2faRoute
  '/settings/': typeof appSettingsIndexRoute
  '/login/': typeof loginLoginIndexRoute
  '/onboarding/': typeof loginOnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof landingIndexRoute
  '/settings/about': typeof appSettingsAboutRoute
  '/settings/account': typeof appSettingsAccountRoute
  '/settings/general': typeof appSettingsGeneralRoute
  '/settings/privacy': typeof appSettingsPrivacyRoute
  '/settings/profile': typeof appSettingsProfileRoute
  '/auth/2fa': typeof loginAuth2faRoute
  '/settings': typeof appSettingsIndexRoute
  '/login': typeof loginLoginIndexRoute
  '/onboarding': typeof loginOnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(landing)': typeof landingRouteRouteWithChildren
  '/(login)': typeof loginRouteRouteWithChildren
  '/(landing)/': typeof landingIndexRoute
  '/(app)/settings/about': typeof appSettingsAboutRoute
  '/(app)/settings/account': typeof appSettingsAccountRoute
  '/(app)/settings/general': typeof appSettingsGeneralRoute
  '/(app)/settings/privacy': typeof appSettingsPrivacyRoute
  '/(app)/settings/profile': typeof appSettingsProfileRoute
  '/(login)/auth/2fa': typeof loginAuth2faRoute
  '/(app)/settings/': typeof appSettingsIndexRoute
  '/(login)/login/': typeof loginLoginIndexRoute
  '/(login)/onboarding/': typeof loginOnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings/about'
    | '/settings/account'
    | '/settings/general'
    | '/settings/privacy'
    | '/settings/profile'
    | '/auth/2fa'
    | '/settings/'
    | '/login/'
    | '/onboarding/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings/about'
    | '/settings/account'
    | '/settings/general'
    | '/settings/privacy'
    | '/settings/profile'
    | '/auth/2fa'
    | '/settings'
    | '/login'
    | '/onboarding'
  id:
    | '__root__'
    | '/(app)'
    | '/(landing)'
    | '/(login)'
    | '/(landing)/'
    | '/(app)/settings/about'
    | '/(app)/settings/account'
    | '/(app)/settings/general'
    | '/(app)/settings/privacy'
    | '/(app)/settings/profile'
    | '/(login)/auth/2fa'
    | '/(app)/settings/'
    | '/(login)/login/'
    | '/(login)/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  landingRouteRoute: typeof landingRouteRouteWithChildren
  loginRouteRoute: typeof loginRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(login)': {
      id: '/(login)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof loginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)': {
      id: '/(landing)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof landingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)/': {
      id: '/(landing)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof landingIndexRouteImport
      parentRoute: typeof landingRouteRoute
    }
    '/(login)/onboarding/': {
      id: '/(login)/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof loginOnboardingIndexRouteImport
      parentRoute: typeof loginRouteRoute
    }
    '/(login)/login/': {
      id: '/(login)/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof loginLoginIndexRouteImport
      parentRoute: typeof loginRouteRoute
    }
    '/(app)/settings/': {
      id: '/(app)/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof appSettingsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(login)/auth/2fa': {
      id: '/(login)/auth/2fa'
      path: '/auth/2fa'
      fullPath: '/auth/2fa'
      preLoaderRoute: typeof loginAuth2faRouteImport
      parentRoute: typeof loginRouteRoute
    }
    '/(app)/settings/profile': {
      id: '/(app)/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof appSettingsProfileRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/privacy': {
      id: '/(app)/settings/privacy'
      path: '/settings/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof appSettingsPrivacyRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/general': {
      id: '/(app)/settings/general'
      path: '/settings/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof appSettingsGeneralRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/account': {
      id: '/(app)/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof appSettingsAccountRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/about': {
      id: '/(app)/settings/about'
      path: '/settings/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof appSettingsAboutRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appSettingsAboutRoute: typeof appSettingsAboutRoute
  appSettingsAccountRoute: typeof appSettingsAccountRoute
  appSettingsGeneralRoute: typeof appSettingsGeneralRoute
  appSettingsPrivacyRoute: typeof appSettingsPrivacyRoute
  appSettingsProfileRoute: typeof appSettingsProfileRoute
  appSettingsIndexRoute: typeof appSettingsIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appSettingsAboutRoute: appSettingsAboutRoute,
  appSettingsAccountRoute: appSettingsAccountRoute,
  appSettingsGeneralRoute: appSettingsGeneralRoute,
  appSettingsPrivacyRoute: appSettingsPrivacyRoute,
  appSettingsProfileRoute: appSettingsProfileRoute,
  appSettingsIndexRoute: appSettingsIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface landingRouteRouteChildren {
  landingIndexRoute: typeof landingIndexRoute
}

const landingRouteRouteChildren: landingRouteRouteChildren = {
  landingIndexRoute: landingIndexRoute,
}

const landingRouteRouteWithChildren = landingRouteRoute._addFileChildren(
  landingRouteRouteChildren,
)

interface loginRouteRouteChildren {
  loginAuth2faRoute: typeof loginAuth2faRoute
  loginLoginIndexRoute: typeof loginLoginIndexRoute
  loginOnboardingIndexRoute: typeof loginOnboardingIndexRoute
}

const loginRouteRouteChildren: loginRouteRouteChildren = {
  loginAuth2faRoute: loginAuth2faRoute,
  loginLoginIndexRoute: loginLoginIndexRoute,
  loginOnboardingIndexRoute: loginOnboardingIndexRoute,
}

const loginRouteRouteWithChildren = loginRouteRoute._addFileChildren(
  loginRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  landingRouteRoute: landingRouteRouteWithChildren,
  loginRouteRoute: loginRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
